namespace Euler
{
    // Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
    // 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    // By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

    internal class Problem002_Even_Fibonacci_numbers
    {
        public static long Solution()
        {
            long sum = 0;
            int prevFib = 1;
            int lastFib = 2;
            while (lastFib < 4000000)
            {
                if (lastFib % 2 == 0) sum += lastFib;
                int temp = lastFib;
                lastFib = prevFib + lastFib;
                prevFib = temp;
            }

            return sum;
        }
    }
}
